import type { NextPage } from "next";
import Head from "next/head";
import Hero from  "../components/Hero";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen">
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <section id="hero">
        <Hero/>
      </section>
    </div>
  );
};

export default Home;
